- hosts: local
  connection: local
  become: yes
  tasks:
    - name: Install Java
      yum:
        name:
          - wget
          - java-1.8.0-openjdk
    - name: Download Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import Jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true
